### ISSUE TITLE
Question: Are module exports and imports permitted

### ISSUE THREAD

**Issue by guybedford** [WebAssembly/module-linking#31]
While there are examples in the explainer of importing and exporting module instances using double-level exports, I couldn't tell from reading the explainer document if there are plans to support exporting and importing modules using double-level imports.

Specifically, would the following be considered valid under this spec:

a.wasm
```wat
(module
  (export "m" (module
    (func (export "hi")
      ...
    )
  )
)
```

Then imported via:
```wat
(module
  (import "./a.wasm" "m" (module $a (module (export "m") (func (export "hi") ... ))))
  ...
)
```

**Comment by lukewagner** [comment]
Yes, the nesting you show is intended to be supported.  AFAICS, there wouldn't be any desugaring associated with these two-level modules, though (as there are from two-level imports into imports-of-instances-exporting-fields).

**Comment by guybedford** [comment]
Thanks, that is great to hear, closing as answered.

> (as there are from two-level imports into imports-of-instances-exporting-fields).

Just to make sure I'm understanding, are you referring to treating two-level imports as a sugar for a single-level import + an alias?

**Comment by lukewagner** [comment]
Yep!
