### ISSUE TITLE
Reconsider ESM integration default export usage

### ISSUE THREAD

**Issue by guybedford** [WebAssembly/module-linking#32]
In the JS ecosystem, `default` exports have caused a lot of frictions with CommonJS interop paths. Specifically because `"default"` is just another export name and not a special symbol so it collides with user code. This is a massive pain point right now. For example, the CommonJS module:

```js
exports.default = function f () {
}
```

is treated as different module namespace representations between some tooling and Node.js, since Node.js sees the above module as `Module { default: { default: f () } }`, while some tools expect this to be represented as `Module { default: f () }`. More info here - https://nodejs.org/dist/latest-v16.x/docs/api/esm.html#esm_commonjs_namespaces.

I would strongly suggest Web Assembly does not make the same mistake here. The single-import pattern is more like a namespace import than a default import anyway and this is well represented by the proposed adjustment to the JS API representation of imports in the spec here.

Specifically, the following comment with regards to the ESM integration hits this issue:

> For ESM-integration, single-level imports could potentially map to the ESM default export.

This would by definition override any `default` export of the Wasm module instance being stored in the module map, causing a collision with any WebAssembly module double-level import to the same module that happens to want to import a function called `"default"` from the instance.

Instead, rather than directly referencing the ESM module map in the explainer which is currently effectively an instance map, that it could be better to simply refer to the ESM integration as being able to return the `WebAssembly.Module` instead of the `WebAssembly.Instance` and to instead deal with the details of the implementation in the ESM integration itself. The issue of the cached module versus the cached instance also comes up in the Realms spec so I tend to think this is something that could be a useful abstraction to work towards in the ESM modules spec more generally anyway.

Finally, for the text `Any other type of import is treated as a regular import of the default export.` is also possibly a conflation of the _namespace_ and the _export named `"default"`_. On the one hand this could be very useful as it allows `export default wasmInstance` / `export default wasmModule` workflows, although ideally `export { wasmInstance, wasmModule }` should be equivalently referenceable anyway via the double-import reference and I posted a question about the viability of this workflow in https://github.com/WebAssembly/module-linking/issues/31. Assuming that is allowed then it could also be useful to reserve the ability for namespace instance imports of JS modules as a JS module namespace object reference in future, allowing eg access to live bindings via a JS member get. So disabling single-import modules where the resolved module is not a Wasm module for now might be beneficial, so long as all use cases involving JS exports are still possible with the module / instance on the double import form anyway per that other issue.

**Comment by lukewagner** [comment]
I can definitely see the hazard you describe with different interpretations of the `default` name when it comes to *exports*.  As far as I know, the module-linking explainer doesn't propose anything in this direction, but maybe I'm missing/forgetting something?

For *imports*, however, I don't see the hazard.  E.g., in JS you can write both `import {default} from 'bar';` and `import f from 'bar';` and, IIUC, these both end up referring to the same `default` named export of `bar`.  My understanding was that this is essentially what ESM-integration is proposing: with `(import $f "bar" "default" ...)` corresponding to `import {default as f} from 'bar';` and `(import $f "bar" ...)` corresponding to `import f from 'bar';`.  Is there some separate hazard with this?

**Comment by guybedford** [comment]
> As far as I know, the module-linking explainer doesn't propose anything in this direction, but maybe I'm missing/forgetting something?

The suggestion would just be to remove this line - https://github.com/WebAssembly/module-linking/blame/master/proposals/module-linking/Explainer.md#L195.

> For imports, however, I don't see the hazard.

Agreed there is no hazard with imports, there is however a natural symmetry between namespaces (`import * as ns from 'mod'`). The behaviours in this spec for single-level imports and exports matching namespaces not the `"default"` which was designed for a very specific CommonJS interop problem, and didn't actually solve that very well.

The behaviours here that align with namespaces over default are:
* The single level export of an instance is like a namespace export.
* The single level JS API import form is like setting the namespace.

Extending this natural symmetry to the import of non-Wasm from Wasm would imply that a single-level import of a JS module would return that namespace (`import * as ns from 'mod'`) rather than the `default`. So I was wondering if that is a useful feature as getting the JS namespace via the import syntax would be a new capability that eg might enable live binding access were Wasm to have access to an `Object.Get` function to apply to it. Perhaps for things like JSON modules that only have a `"default"`, it might be more useful to get the default rather than explicitly referencing the default, but still at a conceptual level this is convenience and an exception to the overall symmetry of namespace treatment.

The overall argument being just to discourage any magic `"default"` handling and instead seeing it as being more like namespaces wherever possible, to try not to end up with the same confusions that JS ended up hitting (and thankfully for JS all confusions restricted to legacy paths at least).

**Comment by lukewagner** [comment]
Ah ok, it makes sense to say that the natural/default result of a single-level import is a namespace object.  I wonder if it might make sense, though, to say "if the import would fail, because the namespace object fails to satisfy the import type (which is almost all wasm types -- I expect the only type a namespace object could satisfy is `(global externref)`), then there is a fallback to extracting the default export (in ESM-integration)", and this would be useful for JS because it would allow ESMs to implement, e.g., single-level function imports.

**Comment by guybedford** [comment]
That definitely makes sense from an interop perspective in being able to provide the expected API for a single-level Wasm import from JS through the default export, and yes that sounds like exactly the right sort of wording to note that this is breaking symmetry in order to provide a convenience. Note though that it still wouldn't be possible for JS exporters to provide different interfaces for an instance versus a module import though, so it still doesn't necessarily completely close the loop on such a JS virtualization.

It is also worth considering that JS namespaces will likely have to integrate into Wasm at some point via dynamic import though, so worth thinking ahead to that from this symmetry perspective as well. Perhaps even in an ideal world Wasm Instances and JS module Instances could be typed in the same way as instance namespaces, regardless of the definition language.

**Comment by lukewagner** [comment]
I think this issue is resolved by #37.
